import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import MapDashboard from './components/MapDashboard';
import './index.css';
import './App.css';
import {
  Activity, AlertTriangle, BarChart3, Bell, ChevronRight, CircleGauge,
  Command, Cpu, Database, Gauge, Home, Layers3, MapPinned, Menu, Moon,
  Network, Radio, RefreshCw, Search, Settings, ShieldCheck, Sun, Target,
  Truck, Wifi, X, Zap
} from 'lucide-react';

const API_BASE = import.meta.env.VITE_API_BASE || 'http://localhost:5000';
const BASE_STATION = { id:'GATEWAY', name:'SENTRY Gateway / HQ', lat:32.2396, lng:77.1887, elevation:'2,050 m MSL', status:'ONLINE' };

const INITIAL_NODES = [
  {id:'N01',meshId:'MESH-01',meshName:'North Ridge Mesh',name:'North Ridge Relay',lat:32.3580,lng:77.2215,elevation:'3,320 m',temp:-2.4,humidity:82,pressure:684.5,waterLevel:1.1,windSpeed:42.5,battery:94,rssi:-72,status:'WARNING',hazard:'Seismic movement detected',meshNeighbors:['N02','N03']},
  {id:'N02',meshId:'MESH-01',meshName:'North Ridge Mesh',name:'Upper Ridge Post',lat:32.3640,lng:77.1980,elevation:'3,410 m',temp:-1.2,humidity:79,pressure:677.2,waterLevel:.8,windSpeed:31.2,battery:91,rssi:-66,status:'NORMAL',hazard:'Perimeter monitoring active',meshNeighbors:['N01','N04']},
  {id:'N03',meshId:'MESH-01',meshName:'North Ridge Mesh',name:'Ridge Saddle',lat:32.3385,lng:77.1570,elevation:'3,060 m',temp:1.8,humidity:75,pressure:701.4,waterLevel:1.6,windSpeed:28.1,battery:87,rssi:-79,status:'NORMAL',hazard:'Perimeter monitoring active',meshNeighbors:['N01','N04']},
  {id:'N04',meshId:'MESH-01',meshName:'North Ridge Mesh',name:'Northern Chokepoint',lat:32.3160,lng:77.1775,elevation:'2,820 m',temp:3.8,humidity:76,pressure:725.1,waterLevel:2.4,windSpeed:26.4,battery:83,rssi:-74,status:'WARNING',hazard:'Abnormal vibration signature',meshNeighbors:['N02','N03']},
  {id:'N05',meshId:'MESH-02',meshName:'Central Corridor Mesh',name:'Central Sector East',lat:32.2535,lng:77.1842,elevation:'2,040 m',temp:14.2,humidity:94,pressure:795.0,waterLevel:5.2,windSpeed:22.4,battery:86,rssi:-64,status:'CRITICAL',hazard:'Multiple movement signatures detected',meshNeighbors:['N06','N07']},
  {id:'N06',meshId:'MESH-02',meshName:'Central Corridor Mesh',name:'Central Sector West',lat:32.2680,lng:77.1640,elevation:'2,110 m',temp:12.4,humidity:91,pressure:787.5,waterLevel:3.7,windSpeed:19.8,battery:89,rssi:-61,status:'WARNING',hazard:'Unusual activity detected in sector',meshNeighbors:['N05','N08']},
  {id:'N07',meshId:'MESH-02',meshName:'Central Corridor Mesh',name:'Central Checkpoint',lat:32.2390,lng:77.1575,elevation:'1,980 m',temp:16.5,humidity:87,pressure:802.2,waterLevel:2.2,windSpeed:17.4,battery:95,rssi:-58,status:'NORMAL',hazard:'Perimeter monitoring active',meshNeighbors:['N05','N08']},
  {id:'N08',meshId:'MESH-02',meshName:'Central Corridor Mesh',name:'Forest Approach',lat:32.2250,lng:77.1760,elevation:'1,920 m',temp:17.1,humidity:83,pressure:807.0,waterLevel:1.8,windSpeed:15.6,battery:90,rssi:-69,status:'NORMAL',hazard:'Perimeter monitoring active',meshNeighbors:['N06','N07']},
  {id:'N09',meshId:'MESH-03',meshName:'Valley Approach Mesh',name:'Valley Gate East',lat:32.2140,lng:77.1930,elevation:'1,980 m',temp:17.5,humidity:58,pressure:804.1,waterLevel:1.4,windSpeed:12,battery:91,rssi:-58,status:'NORMAL',hazard:'Perimeter monitoring active',meshNeighbors:['N10','N11']},
  {id:'N10',meshId:'MESH-03',meshName:'Valley Approach Mesh',name:'Valley Gate West',lat:32.2025,lng:77.1680,elevation:'1,910 m',temp:18.2,humidity:62,pressure:809.3,waterLevel:1.1,windSpeed:13.8,battery:88,rssi:-63,status:'NORMAL',hazard:'Perimeter monitoring active',meshNeighbors:['N09','N12']},
  {id:'N11',meshId:'MESH-03',meshName:'Valley Approach Mesh',name:'Highway Observation',lat:32.1880,lng:77.2050,elevation:'1,860 m',temp:19.1,humidity:60,pressure:815.4,waterLevel:1.2,windSpeed:18.2,battery:96,rssi:-55,status:'WARNING',hazard:'PIR movement detected',meshNeighbors:['N09','N12']},
  {id:'N12',meshId:'MESH-03',meshName:'Valley Approach Mesh',name:'Southern Relay',lat:32.1765,lng:77.1820,elevation:'1,820 m',temp:19.8,humidity:57,pressure:818.1,waterLevel:0.9,windSpeed:11.4,battery:93,rssi:-62,status:'NORMAL',hazard:'Perimeter monitoring active',meshNeighbors:['N10','N11']}
];

const INITIAL_DRONE = {id:'SENTRY-DRONE-01',model:'SENTRY Autonomous VTOL',trackingEnabled:true,status:'STANDBY',lat:BASE_STATION.lat,lng:BASE_STATION.lng,targetNodeId:null,targetLat:null,targetLng:null,altitude:0,speed:0,heading:45,battery:88};
const meshMeta = [
  {id:'MESH-01',name:'North Ridge Mesh',zone:'Northern ridge and high-altitude perimeter',gateway:'GATEWAY',health:'STABLE'},
  {id:'MESH-02',name:'Central Corridor Mesh',zone:'Central approach and crossing sector',gateway:'GATEWAY',health:'ATTENTION'},
  {id:'MESH-03',name:'Valley Approach Mesh',zone:'Southern valley and highway approach',gateway:'GATEWAY',health:'STABLE'}
];
const makeLog=(source,message,type='INFO',level='NORMAL',nodeId=null)=>({source,message,type,level,nodeId,timestamp:new Date().toLocaleTimeString()});

export default function App(){
  const [nodes,setNodes]=useState(INITIAL_NODES), [drone,setDrone]=useState(INITIAL_DRONE);
  const [page,setPage]=useState('overview'), [selectedNode,setSelectedNode]=useState(INITIAL_NODES[4]), [selectedMesh,setSelectedMesh]=useState('MESH-01');
  const [isSimulating,setIsSimulating]=useState(true), [connectionState,setConnectionState]=useState('SIMULATION'), [theme,setTheme]=useState('dark'), [mobileOpen,setMobileOpen]=useState(false);
  const [logs,setLogs]=useState([makeLog('SYSTEM','SENTRY command center initialized.'),makeLog('MESH-02','Critical alert received from N05.','ALERT','CRITICAL','N05'),makeLog('MESH-01','Warning received from N01.','ALERT','WARNING','N01')]);
  const [historyData,setHistoryData]=useState([{time:'10:00',temp:12,waterLevel:2.1,windSpeed:16},{time:'10:05',temp:12.6,waterLevel:2.5,windSpeed:19},{time:'10:10',temp:13.1,waterLevel:3.2,windSpeed:24},{time:'10:15',temp:13.7,waterLevel:4.1,windSpeed:29}]);
  const [missionEventIndex,setMissionEventIndex]=useState(0);
  const targetNodeRef=useRef(null);
  targetNodeRef.current=nodes.find(n=>n.id===drone.targetNodeId) || null;
  useEffect(()=>document.documentElement.setAttribute('data-theme',theme),[theme]);
  const addLog=useCallback((source,message,type='INFO',level='NORMAL',nodeId=null)=>setLogs(p=>[makeLog(source,message,type,level,nodeId),...p].slice(0,60)),[]);
  const selectNode=useCallback(n=>{if(!n)return;setSelectedNode(n);setSelectedMesh(n.meshId);setPage('node');},[]);
  const openMesh=id=>{setSelectedMesh(id);setPage('mesh');setMobileOpen(false)};
  const meshGroups=useMemo(()=>meshMeta.map(m=>({...m,nodes:nodes.filter(n=>n.meshId===m.id)})),[nodes]);
  const alertNodes=nodes.filter(n=>n.status!=='NORMAL');

  useEffect(()=>{
    if(isSimulating){setConnectionState('SIMULATION');return;}
    let mounted=true;
    Promise.all([fetch(`${API_BASE}/api/nodes`,{cache:'no-store'}).then(r=>r.json()),fetch(`${API_BASE}/api/drone`,{cache:'no-store'}).then(r=>r.json())]).then(([n,d])=>{if(!mounted)return;if(n.nodes)setNodes(n.nodes);if(d.drone)setDrone(d.drone);setConnectionState('CONNECTED')}).catch(()=>mounted&&setConnectionState('OFFLINE'));
    const source=new EventSource(`${API_BASE}/api/stream`);source.onopen=()=>mounted&&setConnectionState('CONNECTED');source.onerror=()=>mounted&&setConnectionState('OFFLINE');source.onmessage=e=>{if(!mounted)return;const d=JSON.parse(e.data);if(d.type==='INITIAL_STATE'){setNodes(d.nodes||[]);setDrone(d.drone||INITIAL_DRONE)}else if(d.type==='NODE_TELEMETRY'){setNodes(p=>p.map(n=>n.id===d.node.id?d.node:n));if(d.node.status!=='NORMAL')addLog(d.node.id,`${d.node.status}: ${d.node.hazard||'Sensor threshold exceeded'}`,'ALERT',d.node.status,d.node.id)}else if(d.type==='DRONE_LOG'){if(d.log)addLog(d.log.source,d.log.message,d.log.type,d.log.level,d.log.nodeId)}else if(d.type?.startsWith('DRONE'))setDrone(d.drone)};
    return()=>{mounted=false;source.close()};
  },[isSimulating,addLog]);

  useEffect(()=>{if(!isSimulating)return;const timer=setInterval(()=>{
    setNodes(prev=>prev.map(n=>{const temp=Number((n.temp+(Math.random()-.5)*.12).toFixed(1));const water=Number(Math.max(0,n.waterLevel+(Math.random()-.5)*.025).toFixed(2));const wind=Number(Math.max(0,n.windSpeed+(Math.random()-.5)*.35).toFixed(1));const status=(water>4||wind>35||temp>40)?'CRITICAL':(water>3||wind>25||temp<0)?'WARNING':'NORMAL';return {...n,temp,waterLevel:water,windSpeed:wind,status}}));
    setDrone(prev=>{if(!prev.targetLat||!prev.targetLng||!['DISPATCHED','RETURNING'].includes(prev.status))return prev;const dl=prev.targetLat-prev.lat,dg=prev.targetLng-prev.lng,dist=Math.hypot(dl,dg),heading=(Math.atan2(dg,dl)*180/Math.PI+360)%360;if(dist<.00035){const ret=prev.status==='RETURNING';addLog('UAV SYSTEM',ret?'Drone returned to HQ':`Drone arrived at ${prev.targetNodeId}`,'DRONE');return {...prev,lat:prev.targetLat,lng:prev.targetLng,status:ret?'STANDBY':'HOVERING',speed:0,altitude:ret?0:45,targetNodeId:ret?null:prev.targetNodeId}}return {...prev,lat:prev.lat+dl*.08,lng:prev.lng+dg*.08,heading:Math.round(heading),speed:prev.status==='RETURNING'?15:12.5,altitude:45}});
    setHistoryData(p=>[...p.slice(-15),{time:new Date().toLocaleTimeString().slice(0,5),temp:Number((nodes.reduce((s,n)=>s+n.temp,0)/Math.max(nodes.length,1)).toFixed(1)),waterLevel:Math.max(...nodes.map(n=>n.waterLevel)),windSpeed:Math.max(...nodes.map(n=>n.windSpeed))}]);
  },900);return()=>clearInterval(timer)},[isSimulating,nodes,addLog]);

  useEffect(()=>{
    if(!isSimulating || !['DISPATCHED','HOVERING'].includes(drone.status) || !drone.targetNodeId) return;
    const events=[
      ['AIRBORNE','UAV cleared HQ perimeter. En route to assigned sector.','DRONE','NORMAL'],
      ['EO/IR ANALYTICS','Person-sized movement detected near assigned sector; track established.','DETECTION','WARNING'],
      ['EO/IR ANALYTICS','Vehicle signature detected in assigned sector; classification pending.','DETECTION','WARNING'],
      ['CLASSIFIER','Armoured-vehicle-class signature detected near assigned sector; confidence 81%.','DETECTION','CRITICAL'],
      ['CLASSIFIER','No additional movement detected within the immediate observation area.','DETECTION','NORMAL'],
      ['UAV SYSTEM','Observation pass complete. Mission remains on station.','DRONE','NORMAL']
    ];
    const timer=setInterval(()=>{
      const target=targetNodeRef.current;
      if(!target) return;
      setMissionEventIndex(i=>{
        const event=events[i%events.length];
        addLog(event[0],`${event[1]} [${target.id}]`,event[2],event[3],target.id);
        return i+1;
      });
    },2600);
    return ()=>clearInterval(timer);
  },[isSimulating,drone.status,drone.targetNodeId,addLog]);

  const dispatch=async nodeId=>{const node=nodes.find(n=>n.id===nodeId);if(!node)return;setSelectedNode(node);if(!isSimulating){try{const r=await fetch(`${API_BASE}/api/drone/dispatch`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nodeId})});const d=await r.json();if(!r.ok)throw Error(d.error);setDrone(d.drone)}catch{addLog('UAV COMMAND','Live controller unavailable. Start gateway server or use simulation.','ALERT','WARNING',nodeId)}return}setDrone(p=>({...p,status:'DISPATCHED',targetNodeId:node.id,targetLat:node.lat,targetLng:node.lng,altitude:45,speed:12.5}));addLog('UAV COMMAND',`Operator dispatched drone to ${node.id} — ${node.name}.`,'DRONE','NORMAL',node.id);setPage('drone');};
  const command=async c=>{if(!isSimulating){try{const r=await fetch(`${API_BASE}/api/drone/command`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:c})});const d=await r.json();if(r.ok)setDrone(d.drone)}catch{}}else if(c==='RTL'){setDrone(p=>({...p,status:'RETURNING',targetNodeId:null,targetLat:BASE_STATION.lat,targetLng:BASE_STATION.lng,speed:15,altitude:45}));addLog('UAV COMMAND','Return-to-HQ command issued.','DRONE')}else if(c==='HOVER')setDrone(p=>({...p,status:'HOVERING',speed:0}));};
  const refresh=()=>{if(isSimulating){addLog('SYSTEM','Simulation telemetry refreshed.');return}Promise.all([fetch(`${API_BASE}/api/nodes`,{cache:'no-store'}).then(r=>r.json()),fetch(`${API_BASE}/api/drone`,{cache:'no-store'}).then(r=>r.json())]).then(([n,d])=>{if(n.nodes)setNodes(n.nodes);if(d.drone)setDrone(d.drone)}).catch(()=>{})};

  const nav=[['overview','Overview',Home],['meshes','Meshes',Network],['node','Nodes',Cpu],['alerts','Alerts',Bell],['drone','Drone Operations',Target],['analytics','Analytics',BarChart3],['system','System',Settings]];
  const title={overview:['Operations Overview','Live command center for deployed sensor meshes and response assets'],meshes:['Mesh Network','All deployed meshes, their nodes and link health'],mesh:['Mesh Detail',meshMeta.find(m=>m.id===selectedMesh)?.name||'Selected mesh'],node:['Node Detail',selectedNode?.name||'Selected sensor node'],alerts:['Alerts & Events','Review warnings, critical events and operator actions'],drone:['Drone Operations','Dispatch, track and control the response UAV'],analytics:['Telemetry & Analytics','Operational trends across the sensor network'],system:['System Status','Gateway, connectivity and deployment configuration']}[page]||['SENTRY',''];
  const go=p=>{setPage(p);setMobileOpen(false)};

  return <div className="app-shell">
    <aside className={`sidebar ${mobileOpen?'open':''}`}>
      <div className="brand"><div className="brand-mark"><ShieldCheck size={21}/></div><div><strong>SENTRY</strong><span>COMMAND & FIELD OPERATIONS</span></div></div>
      <div className="side-label">COMMAND</div>
      <nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><Icon size={17}/><span>{label}</span>{id==='alerts'&&alertNodes.length>0?<em>{alertNodes.length}</em>:null}</button>)}</nav>
      <div className="sidebar-footer"><div className="gateway-status"><span className="status-dot"></span><div><b>Gateway Online</b><small>{connectionState}</small></div></div><div className="side-note">Private LoRa mesh<br/>Gateway uplink active</div></div>
    </aside>
    {mobileOpen&&<div className="mobile-backdrop" onClick={()=>setMobileOpen(false)}/>} 
    <main className="main-shell">
      <header className="topbar"><div className="top-left"><button className="icon-btn mobile-menu" onClick={()=>setMobileOpen(true)}><Menu size={19}/></button><div><div className="breadcrumb">SENTRY COMMAND / {page.toUpperCase()}</div><h1>{title[0]}</h1><p>{title[1]}</p></div></div><div className="top-actions"><div className="connection"><span className={`status-dot ${connectionState==='OFFLINE'?'offline':''}`}></span><span>{connectionState==='SIMULATION'?'Demo telemetry':connectionState==='CONNECTED'?'Live gateway':'Gateway offline'}</span></div><button className="icon-btn" onClick={refresh} title="Refresh"><RefreshCw size={17}/></button><button className="icon-btn" onClick={()=>setTheme(t=>t==='light'?'dark':'light')} title="Theme">{theme==='light'?<Moon size={17}/>:<Sun size={17}/>}</button></div></header>
      <div className="content">
        {page==='overview'&&<Overview nodes={nodes} meshes={meshGroups} drone={drone} alertNodes={alertNodes} onMesh={openMesh} onNode={selectNode} onAlerts={()=>go('alerts')} onDrone={()=>go('drone')} selectedNode={selectedNode} dispatch={dispatch}/>} 
        {page==='meshes'&&<Meshes meshes={meshGroups} selectedMesh={selectedMesh} onOpen={openMesh}/>} 
        {page==='mesh'&&<MeshDetail mesh={meshGroups.find(m=>m.id===selectedMesh)} allNodes={nodes} drone={drone} selectedNode={selectedNode} onNode={selectNode} onDispatch={dispatch}/>} 
        {page==='node'&&<NodeDetail node={selectedNode} drone={drone} onBack={()=>go('meshes')} onDispatch={dispatch} onDrone={()=>go('drone')}/>} 
        {page==='alerts'&&<AlertsPage logs={logs} nodes={nodes} onNode={selectNode} onDispatch={dispatch}/>} 
        {page==='drone'&&<DronePage drone={drone} target={nodes.find(n=>n.id===drone.targetNodeId)||selectedNode} logs={logs} onDispatch={dispatch} onCommand={command}/>}  
        {page==='analytics'&&<AnalyticsPage nodes={nodes} historyData={historyData}/>} 
        {page==='system'&&<SystemPage nodes={nodes} meshes={meshGroups} connectionState={connectionState} isSimulating={isSimulating} setIsSimulating={setIsSimulating}/>} 
      </div>
    </main>
  </div>;
}

const Status=({value})=><span className={`status-pill ${value==='CRITICAL'?'critical':value==='WARNING'?'warning':'normal'}`}><i/>{value}</span>;
const Stat=({label,value,detail,icon,accent=''})=><div className="stat-card"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong className={accent}>{value}</strong><small>{detail}</small></div></div>;

function Overview({nodes,meshes,drone,alertNodes,onMesh,onNode,onAlerts,onDrone,dispatch}){return <div className="page-stack">
  <section className="stat-grid"><Stat label="MESH NETWORKS" value={meshes.length} detail={`${nodes.length} field nodes deployed`} icon={<Network/>}/><Stat label="ACTIVE ALERTS" value={alertNodes.length} detail={`${alertNodes.filter(n=>n.status==='CRITICAL').length} critical`} icon={<AlertTriangle/>} accent={alertNodes.length?'warning':''}/><Stat label="UAV STATUS" value={drone.status} detail={drone.targetNodeId?`Target ${drone.targetNodeId}`:'Ready for dispatch'} icon={<Target/>}/><Stat label="GATEWAY" value="ONLINE" detail="Private LoRa uplink" icon={<Wifi/>} accent="success"/></section>
  <section className="section-head"><div><h2>Mesh Network Overview</h2><p>Every deployed mesh and every node is visible from this command view.</p></div><button className="btn secondary" onClick={onAlerts}><Bell size={15}/> View alerts</button></section>
  <div className="mesh-grid">{meshes.map(m=><MeshCard key={m.id} mesh={m} onOpen={()=>onMesh(m.id)}/>)}</div>
  <section className="overview-grid"><div className="panel map-panel"><div className="panel-head"><div><h3>Live Field Map</h3><p>All meshes • {nodes.length} nodes • drone telemetry</p></div><button className="btn secondary" onClick={onDrone}><Target size={14}/> Drone operations</button></div><div className="overview-map"><MapDashboard nodes={nodes} drone={drone} baseStation={BASE_STATION} selectedNode={null} onSelectNode={onNode} onDispatchDrone={dispatch} theme="light"/></div></div>
  <div className="panel alert-panel"><div className="panel-head"><div><h3>Priority Alerts</h3><p>Operator review required</p></div><span className="count-badge">{alertNodes.length}</span></div><div className="alert-list">{alertNodes.slice(0,6).map(n=><button className="alert-row" key={n.id} onClick={()=>onNode(n)}><div className={`alert-icon ${n.status==='CRITICAL'?'critical':'warning'}`}><AlertTriangle size={15}/></div><div><b>{n.id} · {n.name}</b><span>{n.hazard}</span><small>{n.meshName}</small></div><ChevronRight size={16}/></button>)}{!alertNodes.length&&<Empty text="No active alerts"/>}</div></div></section>
  <section className="section-head"><div><h2>All Field Nodes</h2><p>Quick access to every node across the deployed meshes.</p></div></section><div className="node-table">{nodes.map(n=><NodeRow key={n.id} node={n} onClick={()=>onNode(n)}/>)}</div>
</div>}

function MeshCard({mesh,onOpen}){const alerts=mesh.nodes.filter(n=>n.status!=='NORMAL').length;const critical=mesh.nodes.filter(n=>n.status==='CRITICAL').length;return <button className="mesh-card" onClick={onOpen}><div className="mesh-card-top"><div className="mesh-icon"><Network size={18}/></div><Status value={critical?'CRITICAL':alerts?'WARNING':'NORMAL'}/></div><div className="mesh-code">{mesh.id}</div><h3>{mesh.name}</h3><p>{mesh.zone}</p><div className="mesh-meta"><span><Cpu size={14}/>{mesh.nodes.length} nodes</span><span><Radio size={14}/>LoRa</span><span><Activity size={14}/>{alerts?`${alerts} alerts`:'Healthy'}</span></div><div className="mesh-progress"><span style={{width:`${Math.max(35,100-alerts*18)}%`}}/></div><div className="mesh-open">Open mesh <ChevronRight size={15}/></div></button>}
function Meshes({meshes,onOpen}){return <div className="page-stack"><div className="intro-row"><div><h2>Deployed Meshes</h2><p>Each mesh contains its complete set of field nodes and neighbour links.</p></div><div className="search-box"><Search size={16}/><input placeholder="Search meshes or sectors..."/></div></div><div className="mesh-grid large">{meshes.map(m=><MeshCard key={m.id} mesh={m} onOpen={()=>onOpen(m.id)}/>)}</div></div>}
function MeshDetail({mesh,allNodes,drone,selectedNode,onNode,onDispatch}){if(!mesh)return null;return <div className="page-stack"><div className="detail-hero"><div><span className="eyebrow">{mesh.id}</span><h2>{mesh.name}</h2><p>{mesh.zone} · Gateway {mesh.gateway}</p></div><Status value={mesh.nodes.some(n=>n.status==='CRITICAL')?'CRITICAL':mesh.nodes.some(n=>n.status!=='NORMAL')?'WARNING':'NORMAL'}/></div><div className="detail-grid"><div className="panel map-panel"><div className="panel-head"><div><h3>Mesh Coverage</h3><p>{mesh.nodes.length} nodes and neighbour links</p></div></div><div className="mesh-map"><MapDashboard nodes={mesh.nodes} drone={drone} baseStation={BASE_STATION} selectedNode={selectedNode?.meshId===mesh.id?selectedNode:null} onSelectNode={onNode} onDispatchDrone={onDispatch}/></div></div><div className="panel"><div className="panel-head"><div><h3>Nodes in this mesh</h3><p>Complete node inventory</p></div></div><div className="node-list">{mesh.nodes.map(n=><NodeRow key={n.id} node={n} onClick={()=>onNode(n)} />)}</div></div></div></div>}
function NodeRow({node,onClick}){return <button className="node-row" onClick={onClick}><div className="node-main"><span className={`node-status ${node.status.toLowerCase()}`}></span><div><b>{node.id}</b><span>{node.name}</span></div></div><div className="node-reading"><span>{node.temp}°C</span><span>{node.battery}%</span><span>{node.rssi} dBm</span></div><Status value={node.status}/><ChevronRight size={15}/></button>}
function NodeDetail({node,onDispatch,onDrone}){
  if(!node)return <Empty text="Select a node from the dashboard."/>;
  const sensors=[['PIR / MOTION',node.pir ?? (node.status==='NORMAL'?'CLEAR':'TRIGGER'),node.status==='NORMAL'?'Normal':'Attention'],['SEISMIC / VIBRATION',node.seismic ?? (node.status==='NORMAL'?'LOW':'HIGH'),node.status==='NORMAL'?'Normal':'Attention'],['THERMAL',node.thermal ?? `${node.temp}°C`,'Live'],['LIDAR',node.lidar ?? 'ACTIVE','Operational']];
  return <div className="page-stack node-page">
    <div className="detail-hero node-hero"><div><span className="eyebrow">{node.meshName} / {node.id}</span><h2>{node.name}</h2><p>{node.hazard} · {node.lat.toFixed(5)}, {node.lng.toFixed(5)}</p></div><div className="hero-actions"><Status value={node.status}/><button className="btn primary" onClick={()=>onDispatch(node.id)}><Target size={15}/> Dispatch drone</button></div></div>
    <div className="node-detail-grid">
      <div className="node-main-column">
        <section className="panel node-section"><div className="panel-head"><div><h3>Live telemetry</h3><p>Current readings received from the edge node</p></div><span className="live-label"><i/>LIVE</span></div><div className="telemetry-cards"><Stat label="TEMPERATURE" value={`${node.temp}°C`} detail="Ambient" icon={<Gauge/>}/><Stat label="HUMIDITY" value={`${node.humidity}%`} detail="Relative humidity" icon={<Activity/>}/><Stat label="BATTERY" value={`${node.battery}%`} detail="Solar node power" icon={<Zap/>}/><Stat label="RADIO" value={`${node.rssi} dBm`} detail="LoRa signal" icon={<Radio/>}/></div></section>
        <section className="panel node-section"><div className="panel-head"><div><h3>Edge sensor status</h3><p>Local sensing and detection layer</p></div></div><div className="sensor-matrix">{sensors.map(([label,value,state])=><div className="sensor-cell" key={label}><div><span>{label}</span><b>{value}</b></div><em className={state==='Attention'?'attention':''}>{state}</em></div>)}</div></section>
        <section className="panel node-section"><div className="panel-head"><div><h3>Field data</h3><p>Location, detection and mesh connectivity</p></div></div><div className="data-grid">{[['GPS',`${Number(node.lat).toFixed(5)}°N, ${Number(node.lng).toFixed(5)}°E`],['Elevation',node.elevation],['Pressure',`${node.pressure} hPa`],['Wind',`${node.windSpeed} km/h`],['Neighbours',(node.meshNeighbors||[]).join(', ')||'None']].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div></section>
      </div>
      <aside className="node-side-column">
        <section className="panel action-panel"><div className="panel-head"><div><h3>Response control</h3><p>Operator actions</p></div></div><div className="response-summary"><span>NODE CONDITION</span><strong className={node.status.toLowerCase()}>{node.status}</strong><p>{node.hazard}</p></div><div className="action-stack"><button className="action-button" onClick={()=>onDispatch(node.id)}><Target/><div><b>Dispatch drone</b><span>Send SENTRY-DRONE-01 to this GPS point</span></div><ChevronRight/></button><button className="action-button" onClick={onDrone}><Truck/><div><b>Open drone operations</b><span>Track mission and return-to-HQ</span></div><ChevronRight/></button></div></section>
        <section className="panel node-side-card"><div className="panel-head"><div><h3>Mesh path</h3><p>Neighbour routing</p></div></div><div className="neighbor-list">{(node.meshNeighbors||[]).map((id,i)=><div key={id}><span>{i+1}</span><b>{id}</b><small>LINK ACTIVE</small></div>)}</div></section>
      </aside>
    </div>
  </div>
}
function AlertsPage({logs,nodes,onNode,onDispatch}){return <div className="page-stack"><div className="section-head"><div><h2>Alerts & Events</h2><p>Latest node warnings, critical events and operator actions.</p></div></div><div className="panel"><div className="event-list">{logs.map((l,i)=><div className="event-row" key={`${l.timestamp}-${i}`}><div className={`event-marker ${l.level==='CRITICAL'?'critical':l.level==='WARNING'?'warning':''}`}></div><div className="event-content"><div><b>{l.source}</b><span>{l.timestamp}</span></div><p>{l.message}</p>{l.nodeId&&<div className="event-actions"><button className="btn small" onClick={()=>onNode(nodes.find(n=>n.id===l.nodeId))}>View node</button><button className="btn small primary" onClick={()=>onDispatch(l.nodeId)}>Dispatch drone</button></div>}</div></div>)}</div></div></div>}
function DronePage({drone,target,logs,onDispatch,onCommand}){const missionLogs=logs.filter(l=>['DRONE','DETECTION'].includes(l.type)||l.source==='CLASSIFIER'||l.source==='EO/IR ANALYTICS').slice(0,10);return <div className="page-stack"><div className="stat-grid"><Stat label="MISSION STATUS" value={drone.status} detail={target?`Target ${target.id}`:'No active target'} icon={<Target/>}/><Stat label="ALTITUDE" value={`${Math.round(drone.altitude||0)} m`} detail="Current AGL" icon={<Gauge/>}/><Stat label="SPEED" value={`${Number(drone.speed||0).toFixed(1)} m/s`} detail="Ground speed" icon={<Zap/>}/><Stat label="BATTERY" value={`${Math.round(drone.battery||0)}%`} detail="UAV remaining" icon={<Activity/>}/></div><div className="detail-grid drone-detail-grid"><div className="panel map-panel"><div className="panel-head"><div><h3>Live Mission Map</h3><p>{target?`Tracking route to ${target.id}`:'Drone standing by at gateway'}</p></div><Status value={drone.status==='STANDBY'?'NORMAL':drone.status==='DISPATCHED'?'WARNING':'NORMAL'}/></div><div className="mission-map"><MapDashboard nodes={target?[target]:[]} drone={drone} baseStation={BASE_STATION} selectedNode={target} onSelectNode={()=>{}} onDispatchDrone={onDispatch}/></div></div><div className="drone-side-stack"><div className="panel action-panel"><div className="panel-head"><div><h3>Flight Control</h3><p>Operator commands</p></div></div>{target&&<div className="target-box"><span>ACTIVE TARGET</span><b>{target.id}</b><p>{target.name}</p><code>{Number(target.lat).toFixed(5)}, {Number(target.lng).toFixed(5)}</code></div>}<button className="btn primary full" disabled={!target} onClick={()=>target&&onDispatch(target.id)}><Target size={15}/> Dispatch / Re-task</button><button className="btn secondary full" onClick={()=>onCommand('HOVER')}><CircleGauge size={15}/> Hold position</button><button className="btn danger full" onClick={()=>onCommand('RTL')}><Home size={15}/> Return to HQ</button></div><div className="panel mission-log"><div className="panel-head"><div><h3>Mission detection log</h3><p>Onboard analytics / operator events</p></div></div><div className="mission-log-list">{missionLogs.length?missionLogs.map((l,i)=><div className="mission-log-row" key={`${l.timestamp}-${i}`}><span className={`mission-log-dot ${l.level?.toLowerCase()||'normal'}`}></span><div><b>{l.source}</b><p>{l.message}</p><small>{l.timestamp}</small></div></div>):<div className="empty">No mission events yet.</div>}</div></div></div></div></div>}
function AnalyticsPage({nodes,historyData}){const avg=nodes.reduce((s,n)=>s+n.temp,0)/nodes.length;return <div className="page-stack"><div className="stat-grid"><Stat label="AVG TEMPERATURE" value={`${avg.toFixed(1)}°C`} detail="Across all nodes" icon={<Gauge/>}/><Stat label="AVG BATTERY" value={`${Math.round(nodes.reduce((s,n)=>s+n.battery,0)/nodes.length)}%`} detail="Node fleet" icon={<Zap/>}/><Stat label="LOWEST RSSI" value={`${Math.min(...nodes.map(n=>n.rssi))} dBm`} detail="Weakest mesh link" icon={<Radio/>}/><Stat label="CRITICAL NODES" value={nodes.filter(n=>n.status==='CRITICAL').length} detail="Immediate review" icon={<AlertTriangle/>}/></div><div className="panel"><div className="panel-head"><div><h3>Telemetry History</h3><p>Recent gateway telemetry samples</p></div></div><div className="chart-bars">{historyData.map((d,i)=><div className="chart-column" key={i}><div className="bar thermal" style={{height:`${Math.min(100,Math.max(0,(d.temp+10)*2.5))}%`}}></div><div className="bar wind" style={{height:`${Math.min(100,d.windSpeed*2)}%`}}></div><span>{d.time}</span></div>)}</div><div className="chart-legend"><span><i className="legend-water"/>Thermal trend</span><span><i className="legend-wind"/>Wind speed</span></div></div><div className="panel"><div className="panel-head"><div><h3>Fleet Telemetry</h3><p>All nodes across all meshes</p></div></div><div className="node-table">{nodes.map(n=><NodeRow key={n.id} node={n} onClick={()=>{}}/>)}</div></div></div>}
function SystemPage({nodes,meshes,connectionState,isSimulating,setIsSimulating}){return <div className="page-stack"><div className="system-grid"><div className="panel system-card"><div className="system-icon"><Database/></div><h3>Gateway</h3><p>SENTRY Gateway / HQ</p><Status value="NORMAL"/><div className="system-detail"><span>Endpoint</span><b>localhost:5000</b></div></div><div className="panel system-card"><div className="system-icon"><Radio/></div><h3>Mesh transport</h3><p>Private LoRa neighbour links</p><Status value="NORMAL"/><div className="system-detail"><span>Networks</span><b>{meshes.length} active meshes</b></div></div><div className="panel system-card"><div className="system-icon"><Wifi/></div><h3>Telemetry</h3><p>{connectionState}</p><Status value={connectionState==='OFFLINE'?'CRITICAL':'NORMAL'}/><div className="system-detail"><span>Nodes</span><b>{nodes.length} reporting</b></div></div></div><div className="panel settings-panel"><div className="panel-head"><div><h3>Demo & connectivity</h3><p>Use simulation for presentations or connect to the gateway for live telemetry.</p></div></div><label className="setting-row"><div><b>Demo simulation</b><span>Generate live-looking node telemetry and drone movement locally.</span></div><label className="switch"><input type="checkbox" checked={isSimulating} onChange={e=>setIsSimulating(e.target.checked)}/><span className="slider"/></label></label><div className="info-callout"><ShieldCheck size={17}/><div><b>Gateway-only external uplink</b><p>Field nodes remain on the private mesh. The dashboard receives external data through the gateway.</p></div></div></div></div>}
function Empty({text}){return <div className="empty"><Database size={22}/><span>{text}</span></div>}
